### ISSUE TITLE
jekyll-paginate gem missing in __config.yml

### ISSUE THREAD

**Issue by ksivam** [msanand/generator-jekyllstarter#3]
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.

**Comment by ksivam** [comment]
pull request sent: https://github.com/msanand/generator-jekyllstarter/pull/6

**Comment by msanand** [comment]
Fixed in #6
