### ISSUE TITLE
Update redcarpet markdown engine and pygments highlighter

### ISSUE THREAD

**Issue by ksivam** [msanand/generator-jekyllstarter#7]
* You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/.

* You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

**Comment by ksivam** [comment]
pull request sent: https://github.com/msanand/generator-jekyllstarter/pull/6

**Comment by msanand** [comment]
Fixed in #6
